In [ ]:
import pandas as pd

In [ ]:
real_sales = pd.read_csv('./REAL_DATA.csv')
display(real_sales.head(5))
display(real_sales.sample(5))
display(real_sales.tail(5))

display(real_sales.isna().sum())
display(real_sales.dtypes)
display(real_sales['state_holiday'].unique())
display(real_sales.describe())
display(real_sales.info())
days_of_week = real_sales['day_of_week'].unique()
days_of_week.sort()
display(days_of_week)

,index,store_ID,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday
0,272371,415,7,01/03/2015,0,0,0,0,0
1,558468,27,7,29/12/2013,0,0,0,0,0
2,76950,404,3,19/03/2014,657,1,1,0,0
3,77556,683,2,29/01/2013,862,1,0,0,0
4,456344,920,3,19/03/2014,591,1,1,0,0

,index,store_ID,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday
21914,236171,351,2,23/09/2014,414,1,0,0,0
35359,64306,259,6,10/05/2014,1948,1,0,0,0
3052,127512,257,4,01/01/2015,0,0,0,a,1
19030,173504,747,1,07/04/2014,575,1,0,0,0
16745,466227,564,6,09/02/2013,520,1,0,0,0

,index,store_ID,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday
71200,59062,441,7,26/10/2014,0,0,0,0,0
71201,687449,377,7,18/08/2013,0,0,0,0,0
71202,207393,15,3,11/06/2014,648,1,0,0,0
71203,233378,950,2,23/04/2013,626,1,1,0,0
71204,85695,932,4,21/11/2013,828,1,1,0,0

index                  0
store_ID               0
day_of_week            0
date                   0
nb_customers_on_day    0
open                   0
promotion              0
state_holiday          0
school_holiday         0
dtype: int64

index                   int64
store_ID                int64
day_of_week             int64
date                   object
nb_customers_on_day     int64
open                    int64
promotion               int64
state_holiday          object
school_holiday          int64
dtype: object

array(['0', 'a', 'b', 'c'], dtype=object)

,index,store_ID,day_of_week,nb_customers_on_day,open,promotion,school_holiday
count,71205.000000,71205.000000,71205.000000,71205.000000,71205.000000,71205.000000,71205.000000
mean,356303.922042,559.239857,4.000955,633.412387,0.830068,0.379735,0.179187
std,205672.881381,322.078792,1.997519,466.753188,0.375576,0.485324,0.383511
min,7.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,177497.000000,281.000000,2.000000,403.000000,1.000000,0.000000,0.000000
50%,356665.000000,557.000000,4.000000,609.000000,1.000000,0.000000,0.000000
75%,534811.000000,839.000000,6.000000,836.000000,1.000000,1.000000,0.000000
max,712027.000000,1115.000000,7.000000,5494.000000,1.000000,1.000000,1.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71205 entries, 0 to 71204
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                71205 non-null  int64
 1   store_ID             71205 non-null  int64
 2   day_of_week          71205 non-null  int64
 3   date                 71205 non-null  object
 4   nb_customers_on_day  71205 non-null  int64
 5   open                 71205 non-null  int64
 6   promotion            71205 non-null  int64
 7   state_holiday        71205 non-null  object
 8   school_holiday       71205 non-null  int64
dtypes: int64(7), object(2)
memory usage: 4.9+ MB

None

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
real_sales_clean = real_sales.drop(columns=['index', 'store_ID', 'date'])
real_sales_fe = pd.get_dummies(real_sales_clean, columns=['state_holiday'], drop_first=True, dtype=int)
display(real_sales_fe)

,day_of_week,nb_customers_on_day,open,promotion,school_holiday,state_holiday_a,state_holiday_b,state_holiday_c
0,7,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0
2,3,657,1,1,0,0,0,0
3,2,862,1,0,0,0,0,0
4,3,591,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...
71200,7,0,0,0,0,0,0,0
71201,7,0,0,0,0,0,0,0
71202,3,648,1,0,0,0,0,0
71203,2,626,1,1,0,0,0,0
71204,4,828,1,1,0,0,0,0

In [31]:
import pickle

with open("sales_model.pkl", "rb") as file:
    model = pickle.load(file)
    
real_sales_predict = model.predict(real_sales_fe)
display(real_sales_predict)

real_sales['sales'] = real_sales_predict
display(real_sales)

display(real_sales.describe())

real_sales.to_csv('group5.csv', index=False, encoding='utf-8')

array([1.4056402e-01, 1.4056402e-01, 6.8011279e+03, ..., 5.5263325e+03,
       6.7742261e+03, 7.8997017e+03], shape=(71205,), dtype=float32)

,index,store_ID,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday,sales
0,272371,415,7,01/03/2015,0,0,0,0,0,0.140564
1,558468,27,7,29/12/2013,0,0,0,0,0,0.140564
2,76950,404,3,19/03/2014,657,1,1,0,0,6801.127930
3,77556,683,2,29/01/2013,862,1,0,0,0,6754.061035
4,456344,920,3,19/03/2014,591,1,1,0,0,6251.329102
...,...,...,...,...,...,...,...,...,...,...
71200,59062,441,7,26/10/2014,0,0,0,0,0,0.140564
71201,687449,377,7,18/08/2013,0,0,0,0,0,0.140564
71202,207393,15,3,11/06/2014,648,1,0,0,0,5526.332520
71203,233378,950,2,23/04/2013,626,1,1,0,0,6774.226074
71204,85695,932,4,21/11/2013,828,1,1,0,0,7899.701660

,index,store_ID,day_of_week,nb_customers_on_day,open,promotion,school_holiday,sales
count,71205.000000,71205.000000,71205.000000,71205.000000,71205.000000,71205.000000,71205.000000,71205.000000
mean,356303.922042,559.239857,4.000955,633.412387,0.830068,0.379735,0.179187,5773.319336
std,205672.881381,322.078792,1.997519,466.753188,0.375576,0.485324,0.383511,3613.073486
min,7.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,-10.810880
25%,177497.000000,281.000000,2.000000,403.000000,1.000000,0.000000,0.000000,4092.979004
50%,356665.000000,557.000000,4.000000,609.000000,1.000000,0.000000,0.000000,5949.385742
75%,534811.000000,839.000000,6.000000,836.000000,1.000000,1.000000,0.000000,7817.601562
max,712027.000000,1115.000000,7.000000,5494.000000,1.000000,1.000000,1.000000,27737.197266